'use client'

import { useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import { Github, X, Loader2, ExternalLink, Lock, Unlock, Check, AlertCircle } from 'lucide-react'
import { projectApi } from '@/lib/api'
import { toast } from '@/lib/hooks/use-toast'

interface GitHubExportModalProps {
  projectId: string
  projectName: string
  trigger?: React.ReactNode
}

/**
 * GitHubExportModal — Modal dialog for exporting project to GitHub.
 * 
 * Collects:
 * - GitHub Personal Access Token (PAT)
 * - Repository name (defaults to project name, sanitized)
 * - Repository description (optional)
 * - Visibility (public/private)
 * 
 * On success, displays link to new repository.
 */
export function GitHubExportModal({ projectId, projectName, trigger }: GitHubExportModalProps) {
  const [open, setOpen] = useState(false)
  const [isExporting, setIsExporting] = useState(false)
  const [exportResult, setExportResult] = useState<{ url: string; name: string } | null>(null)
  const [error, setError] = useState<string | null>(null)

  // Form state
  const [token, setToken] = useState('')
  const [repoName, setRepoName] = useState(sanitizeRepoName(projectName))
  const [description, setDescription] = useState('')
  const [isPrivate, setIsPrivate] = useState(false)

  // Sanitize repo name to valid GitHub format
  function sanitizeRepoName(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9-_]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 100) || 'codeforge-project'
  }

  const handleExport = async () => {
    if (!token.trim()) {
      setError('GitHub Personal Access Token is required')
      return
    }
    if (!repoName.trim()) {
      setError('Repository name is required')
      return
    }

    setIsExporting(true)
    setError(null)

    try {
      const result = await projectApi.exportToGitHub(projectId, {
        repo_name: repoName.trim(),
        description: description.trim() || undefined,
        private: isPrivate,
        github_token: token.trim(),
      })

      setExportResult({
        url: result.repository_url || `https://github.com/${result.owner}/${result.repo_name}`,
        name: result.repo_name || repoName,
      })

      toast.success('Export successful!', `Repository "${repoName}" created on GitHub.`)
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Export failed. Please check your token and try again.'
      setError(message)
      toast.error('Export failed', message)
    } finally {
      setIsExporting(false)
    }
  }

  const handleClose = () => {
    setOpen(false)
    // Reset state after animation
    setTimeout(() => {
      setExportResult(null)
      setError(null)
      setToken('')
    }, 200)
  }

  const handleOpenChange = (newOpen: boolean) => {
    if (newOpen) {
      // Reset and pre-populate when opening
      setRepoName(sanitizeRepoName(projectName))
      setDescription(`Generated by CodeForge AI`)
      setExportResult(null)
      setError(null)
    }
    setOpen(newOpen)
  }

  return (
    <Dialog.Root open={open} onOpenChange={handleOpenChange}>
      <Dialog.Trigger asChild>
        {trigger || (
          <button className="flex items-center justify-center h-8 px-3 bg-muted hover:bg-muted/80 text-foreground rounded-lg transition-colors gap-2 border border-border">
            <Github className="size-4" />
            <span className="text-xs font-medium">Export</span>
          </button>
        )}
      </Dialog.Trigger>

      <Dialog.Portal>
        <Dialog.Overlay className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0" />
        <Dialog.Content className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-full max-w-md bg-background border border-border rounded-xl shadow-2xl p-6 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%]">
          {/* Close button */}
          <Dialog.Close asChild>
            <button
              className="absolute right-4 top-4 p-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
              aria-label="Close"
            >
              <X className="size-4" />
            </button>
          </Dialog.Close>

          {/* Header */}
          <div className="flex items-center gap-3 mb-6">
            <div className="size-10 rounded-lg bg-muted flex items-center justify-center">
              <Github className="size-5 text-foreground" />
            </div>
            <div>
              <Dialog.Title className="text-lg font-bold text-foreground">
                Export to GitHub
              </Dialog.Title>
              <Dialog.Description className="text-sm text-muted-foreground">
                Push your project to a new GitHub repository
              </Dialog.Description>
            </div>
          </div>

          {/* Success state */}
          {exportResult ? (
            <div className="space-y-4">
              <div className="flex items-center gap-3 p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-lg">
                <Check className="size-5 text-emerald-500 shrink-0" />
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-foreground">Repository created!</p>
                  <p className="text-xs text-muted-foreground truncate">{exportResult.name}</p>
                </div>
              </div>

              <a
                href={exportResult.url}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center justify-center gap-2 w-full h-10 bg-foreground text-background rounded-lg font-medium text-sm hover:bg-foreground/90 transition-colors"
              >
                Open Repository
                <ExternalLink className="size-4" />
              </a>

              <button
                onClick={handleClose}
                className="w-full h-10 bg-muted hover:bg-muted/80 text-foreground rounded-lg font-medium text-sm transition-colors"
              >
                Done
              </button>
            </div>
          ) : (
            /* Form */
            <div className="space-y-4">
              {/* Error message */}
              {error && (
                <div className="flex items-start gap-2 p-3 bg-destructive/10 border border-destructive/20 rounded-lg text-sm text-destructive">
                  <AlertCircle className="size-4 shrink-0 mt-0.5" />
                  <span>{error}</span>
                </div>
              )}

              {/* Token input */}
              <div className="space-y-2">
                <label htmlFor="github-token" className="text-sm font-medium text-foreground">
                  Personal Access Token <span className="text-destructive">*</span>
                </label>
                <input
                  id="github-token"
                  type="password"
                  value={token}
                  onChange={(e) => setToken(e.target.value)}
                  placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                  className="w-full h-10 px-3 bg-muted border border-border rounded-lg text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-cf-primary/50 focus:border-cf-primary"
                  autoComplete="off"
                />
                <p className="text-xs text-muted-foreground">
                  Requires <code className="bg-muted px-1 rounded">repo</code> scope.{' '}
                  <a
                    href="https://github.com/settings/tokens/new?scopes=repo&description=CodeForge%20AI%20Export"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-cf-primary hover:underline"
                  >
                    Create token →
                  </a>
                </p>
              </div>

              {/* Repo name input */}
              <div className="space-y-2">
                <label htmlFor="repo-name" className="text-sm font-medium text-foreground">
                  Repository Name <span className="text-destructive">*</span>
                </label>
                <input
                  id="repo-name"
                  type="text"
                  value={repoName}
                  onChange={(e) => setRepoName(sanitizeRepoName(e.target.value))}
                  placeholder="my-awesome-project"
                  className="w-full h-10 px-3 bg-muted border border-border rounded-lg text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-cf-primary/50 focus:border-cf-primary font-mono"
                  maxLength={100}
                />
              </div>

              {/* Description input */}
              <div className="space-y-2">
                <label htmlFor="repo-description" className="text-sm font-medium text-foreground">
                  Description <span className="text-muted-foreground font-normal">(optional)</span>
                </label>
                <input
                  id="repo-description"
                  type="text"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="A brief description of your project"
                  className="w-full h-10 px-3 bg-muted border border-border rounded-lg text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-cf-primary/50 focus:border-cf-primary"
                  maxLength={200}
                />
              </div>

              {/* Visibility toggle */}
              <div className="flex items-center justify-between p-3 bg-muted rounded-lg border border-border">
                <div className="flex items-center gap-2">
                  {isPrivate ? (
                    <Lock className="size-4 text-muted-foreground" />
                  ) : (
                    <Unlock className="size-4 text-muted-foreground" />
                  )}
                  <span className="text-sm font-medium text-foreground">
                    {isPrivate ? 'Private repository' : 'Public repository'}
                  </span>
                </div>
                <button
                  type="button"
                  role="switch"
                  aria-checked={isPrivate}
                  aria-label="Toggle repository visibility"
                  title={isPrivate ? 'Make repository public' : 'Make repository private'}
                  onClick={() => setIsPrivate(!isPrivate)}
                  className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors focus:outline-none focus:ring-2 focus:ring-cf-primary/50 ${
                    isPrivate ? 'bg-cf-primary' : 'bg-muted-foreground/30'
                  }`}
                >
                  <span
                    className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow-lg ring-0 transition-transform ${
                      isPrivate ? 'translate-x-5' : 'translate-x-0'
                    }`}
                  />
                </button>
              </div>

              {/* Submit button */}
              <button
                onClick={handleExport}
                disabled={isExporting || !token.trim() || !repoName.trim()}
                className="flex items-center justify-center gap-2 w-full h-11 bg-foreground text-background rounded-lg font-semibold text-sm hover:bg-foreground/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isExporting ? (
                  <>
                    <Loader2 className="size-4 animate-spin" />
                    Exporting...
                  </>
                ) : (
                  <>
                    <Github className="size-4" />
                    Export to GitHub
                  </>
                )}
              </button>
            </div>
          )}
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}
